name: Events Demo 1
on:
  pull_request:
    types:
      - opened # activity type
  workflow_dispatch: # how add the second event inthis mode
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
# on: [push, workflow_dispatch] : passing multupple events
# passing activity type to and event if available! :
# on:
# pull_request:
#  types: [opened,closed] or above
# the next event must be at the same position as the first one  workflow_dispatch:
